language: java
jdk: oraclejdk8

sudo: false

notifications:
  email:
    recipients:
      - cduarte@unilurio.ac.mz
      - abatalha@unilurio.ac.mz
    on_success: change
    on_failure: always

script:
  - mvn test
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V