language: java

before_script:
  - export TZ=Mocambique/Pemba

jdk: oraclejdk8

sudo: false

notifications:
  email:
    recipients:
      - cduarte@unilurio.ac.mz
      - abatalha@unilurio.ac.mz
    on_success: change
    on_failure: always

script:
  - cd sgb/src/main/test/sgb/report; mvn test -B
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn clean cobertura:cobertura coveralls:report