language: java

before_script:
  - export TZ=Mocambique/Pemba

jdk: oraclejdk8

sudo: false

notifications:
  email:
    recipients:
      - cduarte@unilurio.ac.mz
      - abatalha@unilurio.ac.mz
    on_success: change
    on_failure: always

script:
  - mvn test -B

after_success:
  - mvn clean cobertura:cobertura coveralls:report

install:
  - mvn install -DskipTests=true -Dgpg.skip=true --settings ~/settings.xml