language: java
sudo: true
dist: trusty
jdk:
  - oraclejdk8
#script:
#  - mvn test -B
#  - mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
addons:
  apt:
    packages:
      - oracle-java8-installer
after_success:
  - mvn test jacoco:report coveralls:report